export { default as PostsPage } from './posts'
export { default as EventsPage } from './events'
export { default as InformationPage } from './information'
export { default as BannersPage } from './banners'
export { default as LoginPage } from './login'
export { default as CreateBannerPage } from './banners/create'
export { default as UpdateBannerPage } from './banners/update'
export { default as CreateEventPage } from './events/create'
